export const DOG_BREEDS = [
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Border Collie",
  "Cocker Spaniel",
  "Springer Spaniel",
  "French Bulldog",
  "Bulldog",
  "Beagle",
  "Dachshund",
  "Poodle",
  "Cockapoo",
  "Labradoodle",
  "Cavapoo",
  "Cavalier King Charles Spaniel",
  "Staffordshire Bull Terrier",
  "Chihuahua",
  "Pomeranian",
  "Siberian Husky",
  "Corgi",
  "Mixed Breed",
  "Other",
] as const;

export const CAT_BREEDS = [
  "British Shorthair",
  "Ragdoll",
  "Maine Coon",
  "Persian",
  "Siamese",
  "Bengal",
  "Sphynx",
  "Scottish Fold",
  "Russian Blue",
  "Norwegian Forest Cat",
  "Abyssinian",
  "Birman",
  "Mixed Breed",
  "Other",
] as const;
